/* ===== FIREBASE STORE ===== */
const Store = (() => {
  const state = { users:[], categories:[], products:[], sales:[], movements:[], expenses:[], cashSessions:[], audits:[], currentUser:null, cart:[] };
  const refs = {};
  const limaParts = () => {
    const parts = new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());
    const x=Object.fromEntries(parts.map(p=>[p.type,p.value])); return {fecha:`${x.year}-${x.month}-${x.day}`,hora:`${x.hour}:${x.minute}:${x.second}`};
  };
  const clean = o => JSON.parse(JSON.stringify(o));
  const docId = () => db.collection('_ids').doc().id;
  const isActive = u => String(u?.estado || '').toLowerCase() === 'activo';
  const normalizeUser = u => ({
    ...u,
    nombres: String(u?.nombres || u?.nombre || '').trim(),
    apellidos: String(u?.apellidos || u?.apellido || '').trim(),
    estado: isActive(u) ? 'Activo' : (u?.estado || 'Inactivo')
  });
  function getCategory(id){return state.categories.find(x=>x.id===id)}
  function getProduct(id){return state.products.find(x=>x.id===id)}
  function getUser(id){return state.users.find(x=>x.id===id)}
  function stockStatus(p){return p.stock<=0?'agotado':p.stock<=p.stockMinimo?'bajo':'normal'}
  function lowStockProducts(){return state.products.filter(p=>p.estado==='Activo'&&p.stock<=p.stockMinimo)}
  function listen(name, query=null){ refs[name]?.(); const source=query||db.collection(name); refs[name]=source.onSnapshot(s=>{state[name]=s.docs.map(d=>name==='users'?normalizeUser({id:d.id,...d.data()}):({id:d.id,...d.data()})); if(Auth?.isLoggedIn?.() && Router?.current) Router.go(Router.current);},err=>{console.error('Firestore '+name+':',err); try{Toast.show('Error cargando '+name+': '+(err.message||err),'error')}catch(_){}}); }
  async function loadData(){
    if(state.currentUser?.role==='admin'){ for(const n of ['users','categories','products','sales','movements','expenses','cashSessions']) listen(n); return; }
    listen('categories'); listen('products');
    listen('sales',db.collection('sales').where('empleadoId','==',state.currentUser.id));
    listen('cashSessions',db.collection('cashSessions').where('usuarioId','==',state.currentUser.id));
  }
  function stop(){Object.values(refs).forEach(f=>f&&f()); Object.keys(refs).forEach(k=>delete refs[k]);}
  async function load(){ return new Promise(resolve=>fbAuth.onAuthStateChanged(async u=>{ if(!u){state.currentUser=null;stop();resolve();return;} const d=await db.collection('users').doc(u.uid).get(); if(!d.exists){await fbAuth.signOut();resolve();return;} state.currentUser=normalizeUser({id:u.uid,...d.data()}); if(!isActive(state.currentUser)){await fbAuth.signOut();state.currentUser=null;resolve();return;} await loadData(); resolve(); })); }
  async function login(email,password){try{const c=await fbAuth.signInWithEmailAndPassword(email,password);const d=await db.collection('users').doc(c.user.uid).get();if(!d.exists||!isActive(d.data())){await fbAuth.signOut();return{ok:false,error:'Usuario inactivo o sin perfil'}}state.currentUser=normalizeUser({id:c.user.uid,...d.data()});await loadData();return{ok:true,user:state.currentUser}}catch(e){return{ok:false,error:'Correo o contraseña incorrectos'}}}
  async function logout(){stop();state.cart=[];state.currentUser=null;await fbAuth.signOut()}
  async function audit(accion,detalle){if(!state.currentUser)return;const t=limaParts();await db.collection('audits').add({...t,accion,detalle,usuarioId:state.currentUser.id,usuarioNombre:`${state.currentUser.nombres||''} ${state.currentUser.apellidos||''}`.trim(),createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
  async function addUser(data){try{const secondary=firebase.initializeApp(firebaseConfig,'userCreator-'+Date.now());const cred=await secondary.auth().createUserWithEmailAndPassword(data.email.trim().toLowerCase(),data.password);const user={email:data.email.trim().toLowerCase(),role:'empleado',nombres:data.nombres.trim(),apellidos:data.apellidos.trim(),dni:data.dni.trim(),telefono:data.telefono.trim(),estado:data.estado||'Activo'};await db.collection('users').doc(cred.user.uid).set(user);await secondary.auth().signOut();await secondary.delete();await audit('CREAR_EMPLEADO',user.email);return{ok:true,user:{id:cred.user.uid,...user}}}catch(e){return{ok:false,error:e.message}}}
  async function updateUser(id,data){try{const u=getUser(id);if(!u)return{ok:false,error:'Usuario no encontrado'};const patch={nombres:data.nombres?.trim()??u.nombres,apellidos:data.apellidos?.trim()??u.apellidos,dni:data.dni?.trim()??u.dni,telefono:data.telefono?.trim()??u.telefono,estado:data.estado??u.estado};await db.collection('users').doc(id).update(patch);await audit('EDITAR_EMPLEADO',id);return{ok:true}}catch(e){return{ok:false,error:e.message}}}
  async function deleteUser(id){if(id===state.currentUser?.id)return{ok:false,error:'No puedes desactivar tu propia cuenta'};await db.collection('users').doc(id).update({estado:'Inactivo'});await audit('DESACTIVAR_EMPLEADO',id);return{ok:true}}
  async function addCategory(nombre){const id=docId(),c={nombre:nombre.trim(),estado:'Activo'};await db.collection('categories').doc(id).set(c);await audit('CREAR_CATEGORIA',c.nombre);return{ok:true,category:{id,...c}}}
  async function updateCategory(id,data){await db.collection('categories').doc(id).update(clean(data));await audit('EDITAR_CATEGORIA',id);return{ok:true}}
  async function deleteCategory(id){if(state.products.some(p=>p.categoriaId===id&&p.estado==='Activo'))return{ok:false,error:'La categoría tiene productos activos asociados'};await db.collection('categories').doc(id).update({estado:'Inactivo'});return{ok:true}}
  async function addProduct(data){const id=docId(),stock=Number(data.stock)||0,t=limaParts();const p={nombre:data.nombre.trim(),categoriaId:data.categoriaId,precioCompra:Number(data.precioCompra),precioVenta:Number(data.precioVenta),stock,stockMinimo:Number(data.stockMinimo)||0,descripcion:(data.descripcion||'').trim(),imagen:data.imagen||'📦',estado:data.estado||'Activo'};const b=db.batch();b.set(db.collection('products').doc(id),p);if(stock>0){const mid=docId();b.set(db.collection('movements').doc(mid),{...t,productoId:id,productoNombre:p.nombre,tipo:'Entrada',cantidad:stock,stockAnterior:0,stockNuevo:stock,usuarioId:state.currentUser.id,motivo:'Stock inicial'});if(p.precioCompra>0)b.set(db.collection('expenses').doc(),{...t,concepto:`Stock inicial: ${p.nombre}`,categoria:'Inventario',monto:+(stock*p.precioCompra).toFixed(2),origen:'Stock inicial',usuarioId:state.currentUser.id});}await b.commit();await audit('CREAR_PRODUCTO',p.nombre);return{ok:true,product:{id,...p}}}
  async function updateProduct(id,data){const p=getProduct(id);if(!p)return{ok:false,error:'Producto no encontrado'};const patch={nombre:data.nombre?.trim()??p.nombre,categoriaId:data.categoriaId??p.categoriaId,precioCompra:Number(data.precioCompra??p.precioCompra),precioVenta:Number(data.precioVenta??p.precioVenta),stockMinimo:Number(data.stockMinimo??p.stockMinimo),descripcion:data.descripcion?.trim()??p.descripcion,imagen:data.imagen||p.imagen,estado:data.estado||p.estado};await db.collection('products').doc(id).update(patch);await audit('EDITAR_PRODUCTO',p.nombre);return{ok:true}}
  async function deleteProduct(id){await db.collection('products').doc(id).update({estado:'Inactivo'});await audit('DESACTIVAR_PRODUCTO',id);return{ok:true}}
  async function addMovement({productoId,tipo,cantidad,costoUnitario,motivo}){cantidad=Number(cantidad);if(cantidad<=0)return{ok:false,error:'Cantidad inválida'};const pr=db.collection('products').doc(productoId);try{await db.runTransaction(async tx=>{const s=await tx.get(pr);if(!s.exists)throw Error('Producto no encontrado');const p=s.data(),old=Number(p.stock)||0;const negative=['Salida','Merma','Ajuste -'].includes(tipo);const neu=negative?old-cantidad:old+cantidad;if(neu<0)throw Error('Stock insuficiente');const t=limaParts(),m={...t,productoId,productoNombre:p.nombre,tipo,cantidad,stockAnterior:old,stockNuevo:neu,usuarioId:state.currentUser.id,motivo:motivo||''};tx.update(pr,{stock:neu,...(tipo==='Entrada'&&Number(costoUnitario)>0?{precioCompra:Number(costoUnitario)}:{})});tx.set(db.collection('movements').doc(),m);if(tipo==='Entrada'&&Number(costoUnitario)>0)tx.set(db.collection('expenses').doc(),{...t,concepto:`Compra inventario: ${p.nombre}`,categoria:'Inventario',monto:+(cantidad*Number(costoUnitario)).toFixed(2),origen:'Compra de inventario',usuarioId:state.currentUser.id});});await audit('MOVIMIENTO_STOCK',`${tipo} ${productoId} x${cantidad}`);return{ok:true}}catch(e){return{ok:false,error:e.message}}}
  function addToCart(productoId,qty=1){const p=getProduct(productoId);if(!p||p.estado!=='Activo'||p.stock<=0)return{ok:false,error:'Producto no disponible'};const i=state.cart.find(x=>x.productoId===productoId),n=(i?.cantidad||0)+qty;if(n>p.stock)return{ok:false,error:`Stock insuficiente (disponible: ${p.stock})`};i?i.cantidad=n:state.cart.push({productoId,cantidad:qty});return{ok:true}}
  function updateCartQty(id,c){const p=getProduct(id);if(!p)return{ok:false};if(c<=0)state.cart=state.cart.filter(x=>x.productoId!==id);else{if(c>p.stock)return{ok:false,error:`Máximo ${p.stock} unidades`};const i=state.cart.find(x=>x.productoId===id);if(i)i.cantidad=c;}return{ok:true}}
  function removeFromCart(id){state.cart=state.cart.filter(x=>x.productoId!==id)} function clearCart(){state.cart=[]}
  function getCartTotal(){return state.cart.reduce((s,i)=>s+(getProduct(i.productoId)?.precioVenta||0)*i.cantidad,0)}
  async function confirmSale(metodoPago){if(!state.cart.length)return{ok:false,error:'Carrito vacío'};if(!['Efectivo','Yape','Plin','Tarjeta'].includes(metodoPago))return{ok:false,error:'Método de pago inválido'};const caja=state.cashSessions.find(x=>x.usuarioId===state.currentUser.id&&x.estado==='Abierta');if(!caja)return{ok:false,error:'Debes abrir tu caja antes de registrar una venta'};const saleRef=db.collection('sales').doc();try{await db.runTransaction(async tx=>{const snaps=[];for(const i of state.cart)snaps.push([i,await tx.get(db.collection('products').doc(i.productoId))]);const items=[];let total=0,costo=0;for(const [i,s] of snaps){if(!s.exists||s.data().stock<i.cantidad)throw Error(`Stock insuficiente para ${s.data()?.nombre||'producto'}`);const p=s.data(),sub=p.precioVenta*i.cantidad;items.push({productoId:s.id,nombre:p.nombre,cantidad:i.cantidad,precioUnitario:p.precioVenta,costoUnitario:p.precioCompra,subtotal:sub});total+=sub;costo+=p.precioCompra*i.cantidad;tx.update(s.ref,{stock:p.stock-i.cantidad});const t=limaParts();tx.set(db.collection('movements').doc(),{...t,productoId:s.id,productoNombre:p.nombre,tipo:'Venta',cantidad:i.cantidad,stockAnterior:p.stock,stockNuevo:p.stock-i.cantidad,usuarioId:state.currentUser.id,motivo:`Venta ${saleRef.id}`});}const t=limaParts();tx.set(saleRef,{...t,numero:`V-${saleRef.id.slice(0,6).toUpperCase()}`,empleadoId:state.currentUser.id,empleadoNombre:`${state.currentUser.nombres} ${state.currentUser.apellidos}`,items,total:+total.toFixed(2),costoTotal:+costo.toFixed(2),metodoPago,estado:'Completada',createdAt:firebase.firestore.FieldValue.serverTimestamp()});});state.cart=[];await audit('VENTA',saleRef.id);return{ok:true,sale:{id:saleRef.id,numero:`V-${saleRef.id.slice(0,6).toUpperCase()}`,metodoPago}}}catch(e){return{ok:false,error:e.message}}}
  async function cancelSale(id,motivo='Sin motivo'){const sr=db.collection('sales').doc(id);try{await db.runTransaction(async tx=>{const s=await tx.get(sr);if(!s.exists)throw Error('Venta no encontrada');const sale=s.data();if(sale.estado==='Anulada')throw Error('La venta ya está anulada');for(const i of sale.items){const pr=db.collection('products').doc(i.productoId),p=await tx.get(pr);if(p.exists){const old=p.data().stock||0;tx.update(pr,{stock:old+i.cantidad});const t=limaParts();tx.set(db.collection('movements').doc(),{...t,productoId:i.productoId,productoNombre:i.nombre,tipo:'Devolución',cantidad:i.cantidad,stockAnterior:old,stockNuevo:old+i.cantidad,usuarioId:state.currentUser.id,motivo:`Anulación ${id}: ${motivo}`});}}tx.update(sr,{estado:'Anulada',motivoAnulacion:motivo,anuladaPor:state.currentUser.id});});await audit('ANULAR_VENTA',`${id}: ${motivo}`);return{ok:true}}catch(e){return{ok:false,error:e.message}}}
  async function addExpense(data){const t=limaParts(),exp={...t,concepto:data.concepto.trim(),categoria:data.categoria,monto:Number(data.monto),origen:'Manual',usuarioId:state.currentUser.id};const r=await db.collection('expenses').add(exp);await audit('GASTO',`${exp.concepto} S/${exp.monto}`);return{ok:true,expense:{id:r.id,...exp}}}
  function today(){return limaParts().fecha} function salesToday(){return state.sales.filter(s=>s.fecha===today()&&s.estado!=='Anulada')} function expensesToday(){return state.expenses.filter(e=>e.fecha===today())} function totalSales(fn){return (fn?state.sales.filter(fn):state.sales).filter(s=>s.estado!=='Anulada').reduce((a,b)=>a+Number(b.total||0),0)} function totalExpenses(fn){return(fn?state.expenses.filter(fn):state.expenses).reduce((a,b)=>a+Number(b.monto||0),0)}
  async function openCash(initial){initial=Number(initial);if(!Number.isFinite(initial)||initial<0)return{ok:false,error:'Monto inicial inválido'};if(state.cashSessions.some(x=>x.usuarioId===state.currentUser.id&&x.estado==='Abierta'))return{ok:false,error:'Ya tienes una caja abierta'};const t=limaParts();await db.collection('cashSessions').add({...t,usuarioId:state.currentUser.id,usuarioNombre:state.currentUser.nombres,montoInicial:Number(initial),estado:'Abierta'});await audit('ABRIR_CAJA',`S/${initial}`);return{ok:true}}
  async function closeCash(real){real=Number(real);if(!Number.isFinite(real)||real<0)return{ok:false,error:'Efectivo real inválido'};const c=state.cashSessions.find(x=>x.usuarioId===state.currentUser.id&&x.estado==='Abierta');if(!c)return{ok:false,error:'No hay caja abierta'};const ventas=state.sales.filter(s=>s.empleadoId===state.currentUser.id&&s.estado!=='Anulada'&&(`${s.fecha} ${s.hora}`>=`${c.fecha} ${c.hora}`));const efectivo=ventas.filter(s=>s.metodoPago==='Efectivo').reduce((a,b)=>a+b.total,0),esperado=Number(c.montoInicial)+efectivo,dif=Number(real)-esperado,t=limaParts();await db.collection('cashSessions').doc(c.id).update({estado:'Cerrada',fechaCierre:t.fecha,horaCierre:t.hora,efectivoVentas:efectivo,esperado,real:Number(real),diferencia:dif});await audit('CERRAR_CAJA',`Diferencia S/${dif.toFixed(2)}`);return{ok:true,diferencia:dif}}
  return {state,load,login,logout,getCategory,getProduct,getUser,stockStatus,lowStockProducts,addUser,updateUser,deleteUser,addCategory,updateCategory,deleteCategory,addProduct,updateProduct,deleteProduct,addMovement,addToCart,updateCartQty,removeFromCart,clearCart,getCartTotal,confirmSale,cancelSale,addExpense,salesToday,expensesToday,totalSales,totalExpenses,openCash,closeCash,audit};
})();
